CREATE TABLE TBL_PERSON(
    ID_PERSON NUMBER(22) NOT NULL PRIMARY KEY,
    NAME_PERSON VARCHAR2(255) NOT NULL,
    GENDER_PERSON CHAR(1) NULL,
    AGE_PERSON NUMBER(3) NULL,
    IDENTITY_DOCUMENT_PERSON VARCHAR2(20) NULL,
    ADDRESS_PERSON VARCHAR2(400) NOT NULL,
    PHONE_PERSON VARCHAR2(12) NOT NULL
);

CREATE TABLE TBL_CLIENT(
    ID_PERSON NUMBER(22) NOT NULL PRIMARY KEY,
    PASSWORD_CLIENT VARCHAR2(20) NOT NULL,
    STATUS_CLIENT NUMBER(1) NOT NULL,
    FOREIGN KEY (ID_PERSON) REFERENCES TBL_PERSON(ID_PERSON) ON DELETE CASCADE
);

