CREATE TABLE TBL_ACCOUNT(
    ID_ACCOUNT NUMBER(22) NOT NULL PRIMARY KEY,
    CLIENT_ID_ACCOUNT NUMBER(22) NOT NULL,
    NUMBER_ACCOUNT VARCHAR2(6) NOT NULL,
    TYPE_ACCOUNT VARCHAR2(12) NOT NULL,
    INITIAL_BALANCE_ACCOUNT NUMBER(10,2) NOT NULL,
    CURRENT_BALANCE_ACCOUNT NUMBER(10,2) NOT NULL,
    STATUS_ACCOUNT NUMBER(1) NOT NULL,
    FOREIGN KEY (CLIENT_ID_ACCOUNT) REFERENCES TBL_CLIENT(ID_PERSON) ON DELETE CASCADE
);
CREATE TABLE TBL_MOVEMENT(
    ID_MOVEMENT NUMBER(22) NOT NULL PRIMARY KEY,
    DATE_MOVEMENT DATE NOT NULL,
    TYPE_MOVEMENT VARCHAR2(10)  NOT NULL,
    VALUE_MOVEMENT NUMBER(10,2) NOT NULL,
    CURRENT_BALANCE_MOVEMENT NUMBER(10,2) NULL,
    STATUS_MOVEMENT NUMBER(1) NOT NULL,
    ACCOUNT_ID_MOVEMENT NUMBER(22) NOT NULL,
    FOREIGN KEY (ACCOUNT_ID_MOVEMENT) REFERENCES TBL_ACCOUNT(ID_ACCOUNT) ON DELETE CASCADE
);
