CREATE OR REPLACE VIEW REPORT_MOVEMENTS_ACCOUNT
AS
SELECT
    MOV.ID_MOVEMENT,
    TO_CHAR(MOV.DATE_MOVEMENT,'DD/MM/YYYY') DATE_MOVEMENT,
    CL.NAME_PERSON AS CLIENT,
    CL.ID_PERSON CLIENT_ID,
    ACC.NUMBER_ACCOUNT AS ACCOUNT_NUMBER,
    ACC.TYPE_ACCOUNT,
    ACC.INITIAL_BALANCE_ACCOUNT,
    MOV.STATUS_MOVEMENT,
-- MOV.TYPE_MOVEMENT,
    (CASE WHEN MOV.TYPE_MOVEMENT = 'RETIRO' THEN MOV.VALUE_MOVEMENT*-1 ELSE MOV.VALUE_MOVEMENT END) MOVEMENT,
    ACC.CURRENT_BALANCE_ACCOUNT
FROM TBL_MOVEMENT MOV
         JOIN TBL_ACCOUNT ACC ON ACC.ID_ACCOUNT = MOV.ACCOUNT_ID_MOVEMENT
         JOIN TBL_PERSON CL ON CL.ID_PERSON = ACC.CLIENT_ID_ACCOUNT
ORDER BY DATE_MOVEMENT;